- name: Install prereqs
  apt: package={{ item }} state=present
  with_items:
    - software-properties-common
    - python-software-properties

- name: Installing nginx by apt-get
  apt: name=nginx state=installed

- name: Creating nginx config file
  template: src={{ nginx_conf_file_template }} dest={{ nginx_conf_abs_path }} mode=0655 backup=yes
  notify:
    - restart nginx

- name: Copy htpasswd into /etc/nginx
  template: "src={{ nginx_passwd_file_template }} dest={{ nginx_htpasswd_abs_path }} mode=0655"
  when: nginx_passwd is defined

- name: 'Disable the "default" nginx site'
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - reload nginx

- name: Create the configurations for sites
  template: "src={{ item['nginx_site_file_template'] }} dest=/etc/nginx/sites-available/{{ item['file_name'] }} mode=0655 backup=yes"
  with_items: "{{ nginx_sites }}"
  when: nginx_sites is defined
  notify:
    - reload nginx

- name: Link the configurations for sites
  file: "state=link path=/etc/nginx/sites-enabled/{{ item['file_name'] }} src=/etc/nginx/sites-available/{{ item['file_name'] }}"
  with_items: "{{ nginx_sites }}"
  when: nginx_sites is defined
